import { SourceCatalogEntrySchema } from "./schemas/source-plan";
import type { SourceCatalogEntry } from "../../types/source-plan";

const entry = (value: SourceCatalogEntry): SourceCatalogEntry => SourceCatalogEntrySchema.parse(value);
const zeroCost = { amount: 0, currency: "USD" };
const globalProfiles = ["EN_DISCOVERY_ONLY"] as const;
const regionalProfiles = ["CIS_RU", "LOCAL_CUSTOM"] as const;
const allSignals = ["EXPRESSED_INTENT", "BUSINESS_EVENT", "DETECTED_PROBLEM", "MARKET_OBSERVATION"] as const;

export const DEFAULT_SOURCE_CATALOG: SourceCatalogEntry[] = [
  entry({ providerKey: "official_company_site", sourceFamily: "OFFICIAL_SITE", accessMode: "PUBLIC_WEB", state: "PLANNED", legalStatus: "ALLOWED", costClass: "FREE", configuredCost: zeroCost, marketProfileIds: ["EN_DISCOVERY_ONLY", "CIS_RU", "LOCAL_CUSTOM"], languages: ["*"], businessTypes: ["ALL"], signalFamilies: [...allSignals], priority: 5, rationale: "Identity, product, public contact and offer-relevant first-party evidence." }),
  entry({ providerKey: "public_web_search", sourceFamily: "PUBLIC_WEB", accessMode: "SEARCH_INDEX", state: "PLANNED", legalStatus: "ALLOWED", costClass: "FREE_TIER", configuredCost: zeroCost, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["ALL"], signalFamilies: [...allSignals], priority: 10, rationale: "Broad public discovery and corroboration across company-controlled and independent pages." }),
  entry({ providerKey: "reddit", sourceFamily: "COMMUNITY", accessMode: "OFFICIAL_API", state: "MISSING_CREDENTIALS", legalStatus: "ALLOWED", costClass: "FREE_TIER", configuredCost: zeroCost, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["SAAS", "AGENCY", "CONSULTING"], signalFamilies: ["EXPRESSED_INTENT", "DETECTED_PROBLEM", "MARKET_OBSERVATION"], priority: 20, rationale: "Public expressed pain, comparisons and solution searches." }),
  entry({ providerKey: "hackernews", sourceFamily: "COMMUNITY", accessMode: "OFFICIAL_API", state: "DISABLED", legalStatus: "ALLOWED", costClass: "FREE", configuredCost: zeroCost, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["SAAS"], signalFamilies: ["EXPRESSED_INTENT", "BUSINESS_EVENT", "DETECTED_PROBLEM"], priority: 22, rationale: "Adapter exists, but live access remains disabled until its explicit enablement gate." }),
  entry({ providerKey: "github", sourceFamily: "DEVELOPER", accessMode: "OFFICIAL_API", state: "PLANNED", legalStatus: "ALLOWED", costClass: "FREE_TIER", configuredCost: zeroCost, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["SAAS"], signalFamilies: ["EXPRESSED_INTENT", "BUSINESS_EVENT", "DETECTED_PROBLEM"], priority: 24, rationale: "Issues, discussions and project changes with inspectable provenance." }),
  entry({ providerKey: "stackexchange", sourceFamily: "DEVELOPER", accessMode: "OFFICIAL_API", state: "PLANNED", legalStatus: "ALLOWED", costClass: "FREE_TIER", configuredCost: zeroCost, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["SAAS"], signalFamilies: ["EXPRESSED_INTENT", "DETECTED_PROBLEM"], priority: 26, rationale: "Structured technical questions and recurring implementation pain." }),
  entry({ providerKey: "company_rss_blogs", sourceFamily: "NEWS", accessMode: "PUBLIC_WEB", state: "PLANNED", legalStatus: "ALLOWED", costClass: "FREE", configuredCost: zeroCost, marketProfileIds: ["EN_DISCOVERY_ONLY", "CIS_RU"], languages: ["*"], businessTypes: ["ALL"], signalFamilies: ["BUSINESS_EVENT", "MARKET_OBSERVATION"], priority: 27, rationale: "First-party launches, changelogs, expansion and company announcements." }),
  entry({ providerKey: "greenhouse", sourceFamily: "JOBS", accessMode: "OFFICIAL_API", state: "PLANNED", legalStatus: "ALLOWED", costClass: "FREE", configuredCost: zeroCost, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["ALL"], signalFamilies: ["BUSINESS_EVENT", "DETECTED_PROBLEM"], priority: 28, rationale: "Structured public job-board evidence from participating companies." }),
  entry({ providerKey: "lever", sourceFamily: "JOBS", accessMode: "OFFICIAL_API", state: "PLANNED", legalStatus: "ALLOWED", costClass: "FREE", configuredCost: zeroCost, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["ALL"], signalFamilies: ["BUSINESS_EVENT", "DETECTED_PROBLEM"], priority: 29, rationale: "Structured public job-board evidence from participating companies." }),
  entry({ providerKey: "ashby", sourceFamily: "JOBS", accessMode: "OFFICIAL_API", state: "PLANNED", legalStatus: "ALLOWED", costClass: "FREE", configuredCost: zeroCost, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["ALL"], signalFamilies: ["BUSINESS_EVENT", "DETECTED_PROBLEM"], priority: 30, rationale: "Structured public job-board evidence from participating companies." }),
  entry({ providerKey: "public_career_pages", sourceFamily: "JOBS", accessMode: "PUBLIC_WEB", state: "PLANNED", legalStatus: "ALLOWED", costClass: "FREE", configuredCost: zeroCost, marketProfileIds: ["EN_DISCOVERY_ONLY", "CIS_RU"], languages: ["*"], businessTypes: ["ALL"], signalFamilies: ["BUSINESS_EVENT", "DETECTED_PROBLEM"], priority: 30, rationale: "Current hiring activity as evidence of investment, pressure or capability gaps." }),
  entry({ providerKey: "product_hunt", sourceFamily: "NEWS", accessMode: "OFFICIAL_API", state: "PLANNED", legalStatus: "RESTRICTED", costClass: "UNKNOWN", configuredCost: zeroCost, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["SAAS"], signalFamilies: ["BUSINESS_EVENT", "MARKET_OBSERVATION"], priority: 35, rationale: "Product launches and category context when current access terms permit." }),
  entry({ providerKey: "global_reviews", sourceFamily: "REVIEWS", accessMode: "PARTNER_API", state: "PLANNED", legalStatus: "RESTRICTED", costClass: "UNKNOWN", configuredCost: zeroCost, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["ALL"], signalFamilies: ["DETECTED_PROBLEM", "MARKET_OBSERVATION"], priority: 40, rationale: "Recurring customer pain and category comparison evidence when access permits." }),
  entry({ providerKey: "exa", sourceFamily: "PUBLIC_WEB", accessMode: "PARTNER_API", state: "PAID_LOCKED", legalStatus: "ALLOWED", costClass: "UNKNOWN", configuredCost: { amount: null, currency: null }, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["ALL"], signalFamilies: [...allSignals], priority: 80, rationale: "Demand-gated public-web search fallback; price must be revalidated before any activation." }),
  entry({ providerKey: "serper", sourceFamily: "PUBLIC_WEB", accessMode: "PARTNER_API", state: "PAID_LOCKED", legalStatus: "ALLOWED", costClass: "UNKNOWN", configuredCost: { amount: null, currency: null }, marketProfileIds: [...globalProfiles], languages: ["en"], businessTypes: ["ALL"], signalFamilies: [...allSignals], priority: 81, rationale: "Demand-gated search fallback; price must be revalidated before any activation." }),
  entry({ providerKey: "yandex_search", sourceFamily: "PUBLIC_WEB", accessMode: "SEARCH_INDEX", state: "PLANNED", legalStatus: "UNASSESSED", costClass: "UNKNOWN", configuredCost: zeroCost, marketProfileIds: [...regionalProfiles], languages: ["ru"], businessTypes: ["ALL"], signalFamilies: [...allSignals], priority: 10, rationale: "Regional public-web discovery and corroboration." }),
  entry({ providerKey: "yandex_maps", sourceFamily: "MAPS", accessMode: "OFFICIAL_API", state: "PLANNED", legalStatus: "UNASSESSED", costClass: "UNKNOWN", configuredCost: zeroCost, marketProfileIds: ["LOCAL_CUSTOM"], languages: ["ru"], businessTypes: ["LOCAL_SERVICE"], signalFamilies: ["DETECTED_PROBLEM", "MARKET_OBSERVATION"], priority: 12, rationale: "Local business identity, listing, review and availability evidence." }),
  entry({ providerKey: "two_gis", sourceFamily: "MAPS", accessMode: "OFFICIAL_API", state: "PLANNED", legalStatus: "UNASSESSED", costClass: "UNKNOWN", configuredCost: zeroCost, marketProfileIds: ["LOCAL_CUSTOM"], languages: ["ru"], businessTypes: ["LOCAL_SERVICE"], signalFamilies: ["DETECTED_PROBLEM", "MARKET_OBSERVATION"], priority: 14, rationale: "Regional local-business listings and review evidence." }),
  entry({ providerKey: "regional_directories", sourceFamily: "DIRECTORIES", accessMode: "PUBLIC_WEB", state: "PLANNED", legalStatus: "UNASSESSED", costClass: "UNKNOWN", configuredCost: zeroCost, marketProfileIds: [...regionalProfiles], languages: ["ru"], businessTypes: ["ALL"], signalFamilies: ["BUSINESS_EVENT", "DETECTED_PROBLEM", "MARKET_OBSERVATION"], priority: 16, rationale: "Market-appropriate company identity and local presence evidence." }),
  entry({ providerKey: "local_reviews", sourceFamily: "REVIEWS", accessMode: "PUBLIC_WEB", state: "PLANNED", legalStatus: "UNASSESSED", costClass: "UNKNOWN", configuredCost: zeroCost, marketProfileIds: ["LOCAL_CUSTOM"], languages: ["ru"], businessTypes: ["LOCAL_SERVICE"], signalFamilies: ["DETECTED_PROBLEM", "MARKET_OBSERVATION"], priority: 18, rationale: "Recurring local customer problems and reputation patterns." }),
  entry({ providerKey: "habr", sourceFamily: "COMMUNITY", accessMode: "PUBLIC_WEB", state: "PLANNED", legalStatus: "UNASSESSED", costClass: "UNKNOWN", configuredCost: zeroCost, marketProfileIds: ["CIS_RU"], languages: ["ru"], businessTypes: ["SAAS", "AGENCY", "CONSULTING"], signalFamilies: ["EXPRESSED_INTENT", "BUSINESS_EVENT", "DETECTED_PROBLEM"], priority: 20, rationale: "Regional technical discussions, launches and operational pain." }),
  entry({ providerKey: "vc_ru", sourceFamily: "COMMUNITY", accessMode: "PUBLIC_WEB", state: "PLANNED", legalStatus: "UNASSESSED", costClass: "UNKNOWN", configuredCost: zeroCost, marketProfileIds: ["CIS_RU"], languages: ["ru"], businessTypes: ["SAAS", "AGENCY", "CONSULTING"], signalFamilies: [...allSignals], priority: 22, rationale: "Regional founder, company, market and commercial discussions." }),
  entry({ providerKey: "public_telegram", sourceFamily: "COMMUNITY", accessMode: "MANUAL_ONLY", state: "MANUAL_ONLY", legalStatus: "RESTRICTED", costClass: "UNKNOWN", configuredCost: zeroCost, marketProfileIds: ["CIS_RU"], languages: ["ru"], businessTypes: ["ALL"], signalFamilies: ["EXPRESSED_INTENT", "BUSINESS_EVENT", "MARKET_OBSERVATION"], priority: 30, rationale: "Potential regional public-channel evidence; enabled only through an authorized access path." }),
];
