import type { ProviderDescriptor } from "./contracts";

const observedAt = "2026-10-08T00:00:00.000Z";
const profiles: ProviderDescriptor["marketProfiles"] = ["EN_DISCOVERY_ONLY", "CIS_RU", "LOCAL_CUSTOM"];
const globalProfiles: ProviderDescriptor["marketProfiles"] = ["EN_DISCOVERY_ONLY"];

function descriptor(value: ProviderDescriptor): ProviderDescriptor {
  return Object.freeze({
    ...value,
    marketProfiles: Object.freeze([...value.marketProfiles]),
    languages: Object.freeze([...value.languages]),
    regions: Object.freeze([...value.regions]),
    jurisdictions: Object.freeze([...value.jurisdictions]),
    configuredCost: Object.freeze({ ...value.configuredCost }),
  }) as ProviderDescriptor;
}

export const PROVIDER_CATALOG: readonly ProviderDescriptor[] = Object.freeze([
  descriptor({ id: "hackernews", version: "algolia-v1", capability: "SOURCE_SEARCH", priority: 10, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "disabled", stateObservedAt: observedAt, stateReason: "Live access is not authorized in the current pilot", retryAfterMs: null, configuredCost: { amount: 0, currency: null } }),
  descriptor({ id: "reddit", version: "oauth-v1", capability: "SOURCE_SEARCH", priority: 20, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "missing_credentials", stateObservedAt: observedAt, stateReason: "Official API credentials and access review required", retryAfterMs: null, configuredCost: { amount: 0, currency: null } }),
  descriptor({ id: "github", version: "rest-v1", capability: "SOURCE_SEARCH", priority: 25, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "disabled", stateObservedAt: observedAt, stateReason: "Adapter is fixture-verified; live access requires an explicit activation gate", retryAfterMs: null, configuredCost: { amount: 0, currency: null } }),
  descriptor({ id: "stackexchange", version: "v2.3", capability: "SOURCE_SEARCH", priority: 26, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "disabled", stateObservedAt: observedAt, stateReason: "Adapter is fixture-verified; live access requires an explicit activation gate", retryAfterMs: null, configuredCost: { amount: 0, currency: null } }),
  descriptor({ id: "official_company_site", version: "public-web-v1", capability: "COMPANY_RESOLUTION", priority: 5, marketProfiles: profiles, languages: ["*"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "planned", stateObservedAt: observedAt, stateReason: "Public-web adapter not implemented yet", retryAfterMs: null, configuredCost: { amount: 0, currency: null } }),
  descriptor({ id: "official_company_site", version: "public-contact-v1", capability: "EMAIL_FIND", priority: 5, marketProfiles: profiles, languages: ["*"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "disabled", stateObservedAt: observedAt, stateReason: "Fixture-verified company role-contact fallback; live web access requires an explicit activation gate", retryAfterMs: null, configuredCost: { amount: 0, currency: null } }),
  descriptor({ id: "public_career_pages", version: "public-web-v1", capability: "SOURCE_SEARCH", priority: 30, marketProfiles: profiles, languages: ["*"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "planned", stateObservedAt: observedAt, stateReason: "Career-page adapter not implemented yet", retryAfterMs: null, configuredCost: { amount: 0, currency: null } }),
  ...(["greenhouse", "lever", "ashby"] as const).map((id, index) => descriptor({ id, version: "public-jobs-v1", capability: "SOURCE_SEARCH", priority: 31 + index, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "planned", stateObservedAt: observedAt, stateReason: "Structured public jobs adapter not implemented yet", retryAfterMs: null, configuredCost: { amount: 0, currency: null } })),
  descriptor({ id: "exa", version: "search-v1", capability: "COMPANY_RESOLUTION", priority: 80, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "paid_locked", stateObservedAt: observedAt, stateReason: "Demand and founder spend gate required", retryAfterMs: null, configuredCost: { amount: null, currency: null } }),
  descriptor({ id: "exa", version: "search-v1", capability: "SOURCE_SEARCH", priority: 80, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "paid_locked", stateObservedAt: observedAt, stateReason: "Demand and founder spend gate required", retryAfterMs: null, configuredCost: { amount: null, currency: null } }),
  descriptor({ id: "serper", version: "search-v1", capability: "COMPANY_RESOLUTION", priority: 81, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "paid_locked", stateObservedAt: observedAt, stateReason: "Demand and founder spend gate required", retryAfterMs: null, configuredCost: { amount: null, currency: null } }),
  descriptor({ id: "serper", version: "search-v1", capability: "SOURCE_SEARCH", priority: 81, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "paid_locked", stateObservedAt: observedAt, stateReason: "Demand and founder spend gate required", retryAfterMs: null, configuredCost: { amount: null, currency: null } }),
  ...(["prospeo", "hunter"] as const).flatMap((id, index) => [
    descriptor({ id, version: "fixture-v1", capability: "EMAIL_FIND", priority: 90 + index, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "UNASSESSED", operationalState: "paid_locked", stateObservedAt: observedAt, stateReason: "Fixture contract, terms and spend gate required", retryAfterMs: null, configuredCost: { amount: null, currency: null } }),
    descriptor({ id, version: "fixture-v1", capability: "EMAIL_VERIFY", priority: 90 + index, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "UNASSESSED", operationalState: "paid_locked", stateObservedAt: observedAt, stateReason: "Fixture contract, terms and spend gate required", retryAfterMs: null, configuredCost: { amount: null, currency: null } }),
  ]),
  descriptor({ id: "apollo", version: "fixture-v1", capability: "PERSON_SEARCH", priority: 92, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "UNASSESSED", operationalState: "paid_locked", stateObservedAt: observedAt, stateReason: "Fixture contract, terms and spend gate required", retryAfterMs: null, configuredCost: { amount: null, currency: null } }),
  descriptor({ id: "apollo", version: "fixture-v1", capability: "EMAIL_FIND", priority: 92, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "UNASSESSED", operationalState: "paid_locked", stateObservedAt: observedAt, stateReason: "Found email still requires independent verification", retryAfterMs: null, configuredCost: { amount: null, currency: null } }),
  descriptor({ id: "openai", version: "fixture-v1", capability: "COMPANY_RESOLUTION", priority: 100, marketProfiles: globalProfiles, languages: ["en"], regions: ["*"], jurisdictions: ["*"], legalStatus: "ALLOWED", operationalState: "paid_locked", stateObservedAt: observedAt, stateReason: "Model calls require a separately configured budget", retryAfterMs: null, configuredCost: { amount: null, currency: null } }),
  descriptor({ id: "regional_news_by", version: "planned-v1", capability: "SOURCE_SEARCH", priority: 50, marketProfiles: ["CIS_RU"], languages: ["ru"], regions: ["BY"], jurisdictions: ["BY"], legalStatus: "UNASSESSED", operationalState: "planned", stateObservedAt: observedAt, stateReason: "Regional adapter is not selected yet", retryAfterMs: null, configuredCost: { amount: null, currency: null } }),
]);
