import type { LandingCopy } from "@/types/landing";

export const landingCopy: Record<"en" | "ru", LandingCopy> = {
  en: {
    eyebrow: "Opportunity intelligence · human-controlled",
    headline: "Find companies with a reason to act.",
    subtitle: "The target workflow: multi-source discovery → evidence → company → buyer → verified contact → grounded draft. You review every result; IntentLead never sends it.",
    inputLabel: "What do you sell, and which businesses should need it?",
    placeholder: "Example: We help regional clinics reduce missed calls and turn more enquiries into booked appointments…",
    marketLabel: "Market",
    markets: { GLOBAL_EN: "Global / English pilot", CIS: "CIS · planned", LOCAL_CUSTOM: "Local business · planned" },
    submit: "Build my first discovery brief",
    signedInSubmit: "Continue in workspace",
    privacy: "Your draft stays in this browser tab until you continue. IntentLead never sends messages.",
    siteHint: "Have a site? Add it in the brief for business context.",
    noSendHint: "No automatic outreach",
    trust: ["Target: 20+ confirmed signals", "Target: evidence attached", "Target: contact verified", "Target: draft grounded"],
    journeyEyebrow: "One evidence chain",
    journeyTitle: "From a public clue to a contact-worthy Opportunity.",
    journeySubtitle: "Not another list of names. Every layer must earn the next one.",
    journey: [
      { step: "01", badge: "Source plan", title: "Search where this market actually talks", description: "The source portfolio changes with the offer, company type, geography, access policy and budget." },
      { step: "02", badge: "Evidence", title: "Confirm the observable reason", description: "Posts, jobs, reviews, websites, directories and events stay attached to their original source and capture time." },
      { step: "03", badge: "Resolution", title: "Resolve the company and buyer", description: "IntentLead separates a plausible match from a proven one and ranks the role responsible for the problem." },
      { step: "04", badge: "Package", title: "Verify contact and ground the opening", description: "The final package shows who, why now, how to reach them and what can be said without making anything up." },
    ],
    proofEyebrow: "Target package",
    proofTitle: "An Opportunity package, not a contact dump.",
    proofSubtitle: "Each layer remains inspectable on its own. A missing or uncertain layer is shown honestly instead of being invented.",
    packageReady: "Human-ready",
    packageBoundary: "Copy or export is allowed after review. Sending, mailbox automation, sequences and delivery tracking are not product capabilities.",
    packageCards: [
      { label: "01 · Signal", title: "Observed reason", summary: "A current, commercially relevant condition supported by public evidence.", items: ["source URL + capture time", "fact separated from inference", "freshness and limitations"] },
      { label: "02 · Company", title: "Resolved account", summary: "The real business behind the signal, checked against your ICP.", items: ["identity and domain", "offer and ICP fit", "duplicates merged"] },
      { label: "03 · Buyer", title: "Relevant person", summary: "The role most likely to own the observed problem — not a generic contact.", items: ["role evidence", "confidence shown", "no invented identity"] },
      { label: "04 · Contact + draft", title: "Ready for review", summary: "A sourced business contact and an opening grounded only in the evidence.", items: ["verification shown", "claim-to-evidence links", "copy or export only"] },
    ],
    sourceEyebrow: "Multi-source by design",
    sourceTitle: "One product, different source portfolios.",
    sourceSubtitle: "The source-plan contract does not force every business through Hacker News. The controlled pilot reports which adapters are ready, planned or unavailable.",
    sourceGroups: [
      { title: "Global B2B · controlled pilot", sources: "Ready: Hacker News · Credentials missing: Reddit · Planned: official sites, public web, GitHub, Stack Overflow, jobs, reviews" },
      { title: "CIS · planned", sources: "Yandex surfaces · 2GIS · Telegram · VK · vc.ru · Habr · regional directories" },
      { title: "Local business · planned", sources: "maps · listings · reviews · official sites · directories · local news" },
    ],
    ctaTitle: "Start with what you sell. Get evidence you can inspect.",
    ctaSubtitle: "The target package includes contacts and drafts. The current controlled runtime stops at assessment; sending always stays with you.",
    cta: "Create a discovery brief",
    footerDescription: "Target workflow: offer and ICP → multi-source evidence → company → buyer → verified contact → grounded draft → human action.",
    footerProduct: "Product",
    footerLegal: "Legal",
    footerWorkspace: "Workspace",
    footerDiscovery: "Discovery brief",
    footerOpportunities: "Opportunities",
    dock: { home: "Home", method: "How it works", example: "Example", start: "Start" },
  },
  ru: {
    eyebrow: "Opportunity intelligence · решение принимает человек",
    headline: "Найдите компании, у которых есть причина действовать.",
    subtitle: "Целевой workflow: multi-source discovery → evidence → компания → buyer → проверенный контакт → grounded draft. Вы проверяете каждый результат; IntentLead ничего не отправляет.",
    inputLabel: "Что вы продаёте и каким компаниям это должно быть нужно?",
    placeholder: "Например: помогаем региональным клиникам не терять входящие обращения и доводить их до записи…",
    marketLabel: "Рынок",
    markets: { GLOBAL_EN: "Global / English pilot", CIS: "СНГ · планируется", LOCAL_CUSTOM: "Локальный бизнес · планируется" },
    submit: "Собрать первый discovery brief",
    signedInSubmit: "Продолжить в кабинете",
    privacy: "Черновик остаётся только в этой вкладке до перехода. IntentLead ничего не отправляет.",
    siteHint: "Есть сайт? Добавьте его в brief для контекста бизнеса.",
    noSendHint: "Без автоматических отправок",
    trust: ["Цель: 20+ подтверждённых сигналов", "Цель: evidence приложено", "Цель: контакт проверен", "Цель: draft grounded"],
    journeyEyebrow: "Одна доказательная цепочка",
    journeyTitle: "От публичной находки до Opportunity, с которой можно работать.",
    journeySubtitle: "Не очередной список имён. Каждый следующий слой нужно подтвердить.",
    journey: [
      { step: "01", badge: "Source plan", title: "Искать там, где живёт этот рынок", description: "Набор источников меняется вместе с оффером, типом бизнеса, географией, правилами доступа и бюджетом." },
      { step: "02", badge: "Evidence", title: "Подтвердить наблюдаемую причину", description: "Посты, вакансии, отзывы, сайты, каталоги и события сохраняются вместе с оригинальным источником и временем." },
      { step: "03", badge: "Resolution", title: "Определить компанию и buyer", description: "IntentLead отличает возможное совпадение от доказанного и ранжирует роль, отвечающую за найденную проблему." },
      { step: "04", badge: "Package", title: "Проверить контакт и первый заход", description: "Итог показывает кого, почему сейчас, как найти и что можно сказать без выдуманной персонализации." },
    ],
    proofEyebrow: "Целевой package",
    proofTitle: "Opportunity package, а не выгрузка контактов.",
    proofSubtitle: "Каждый слой можно проверить отдельно. Отсутствующие или сомнительные данные показываются честно, а не выдумываются.",
    packageReady: "Для решения человеком",
    packageBoundary: "После проверки результат можно скопировать или экспортировать. Отправки, mailbox, sequences и delivery tracking не являются возможностями продукта.",
    packageCards: [
      { label: "01 · Сигнал", title: "Наблюдаемая причина", summary: "Актуальное коммерческое условие, подтверждённое публичным evidence.", items: ["source URL и время", "факт отдельно от inference", "свежесть и ограничения"] },
      { label: "02 · Компания", title: "Определённый бизнес", summary: "Реальная компания за сигналом, проверенная на соответствие вашему ICP.", items: ["идентичность и домен", "offer и ICP fit", "дубли объединены"] },
      { label: "03 · Buyer", title: "Подходящий человек", summary: "Роль, отвечающая за найденную проблему, а не случайный контакт.", items: ["evidence роли", "видимая уверенность", "без выдуманных людей"] },
      { label: "04 · Контакт + draft", title: "Готово к проверке", summary: "Контакт с источником и первый заход только на основе evidence.", items: ["статус verification", "claim-to-evidence links", "только copy/export"] },
    ],
    sourceEyebrow: "Multi-source по умолчанию",
    sourceTitle: "Один продукт — разные наборы источников.",
    sourceSubtitle: "Source-plan contract не заставляет любой бизнес проходить через Hacker News. Контролируемый пилот показывает, какие адаптеры готовы, запланированы или недоступны.",
    sourceGroups: [
      { title: "Global B2B · контролируемый пилот", sources: "Готово: Hacker News · Нет credentials: Reddit · Планируется: official sites, public web, GitHub, Stack Overflow, вакансии, reviews" },
      { title: "СНГ · планируется", sources: "Яндекс · 2ГИС · Telegram · VK · vc.ru · Habr · региональные каталоги" },
      { title: "Локальный бизнес · планируется", sources: "карты · карточки · отзывы · официальные сайты · каталоги · местные новости" },
    ],
    ctaTitle: "Начните с того, что продаёте. Получите evidence, которое можно проверить.",
    ctaSubtitle: "Целевой package включает контакты и драфты. Текущий контролируемый runtime останавливается на assessment; отправка всегда остаётся за вами.",
    cta: "Создать discovery brief",
    footerDescription: "Целевой workflow: оффер и ICP → multi-source evidence → компания → buyer → проверенный контакт → grounded draft → действие человека.",
    footerProduct: "Продукт",
    footerLegal: "Документы",
    footerWorkspace: "Рабочее пространство",
    footerDiscovery: "Discovery brief",
    footerOpportunities: "Opportunities",
    dock: { home: "Главная", method: "Как работает", example: "Пример", start: "Начать" },
  },
};
